name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Test and save report to JSON
        run: snyk test --json > snyk-report.json

      - name: Commit and push Snyk report to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snyk-report.json
          git commit -m "Add snyk report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
